### ISSUE TITLE
Bucketname is not prepended to .s3.amazonaws.com

### ISSUE THREAD

**Issue by crystalpaladin** [justafish/drupal_amazons3#22]
The Current version(7.x-2.0-beta2) doesn't seem to prepend the bucket name to the url. But it uploads the file correctly to the amazons3 bucket space

But as a workaround, amazons3 settings->enable cname and configure it as mybucket.s3.amazonaws.com, it works fine... but I don't have any intention of using a CDN and that is a CDN specific setting and enabling that seems to confuse me

The old version of amazons3 module(7.x-1.1) worked fine...

Haven't traced down the exact point yet...

**Comment by crystalpaladin** [comment]
possible points to explore amazons3.module  amazons3_uri_add_bucket() (during file storage)
or amazons3.module amazons3_image_deliver()

**Comment by deviantintegral** [comment]
The URL coming out should be <pre>https://s3.amazonaws.com/bucket/</pre>. So, the bucket shouldn't be prepended, but appended to the URL as a directory. Are you not getting an https URL? Or is bucket missing from the directory path?

**Comment by crystalpaladin** [comment]
my bucket name is news7tamil
when I access the file after enabling the cname and setting it as "news7tamil.s3.amazonaws.com", it works fine ... check out the url: https://news7tamil.s3.amazonaws.com/styles/news7_inner/concept_car_2020-wide.jpg?itok=HVf_codM

but when cname is disabled, The url becomes https://s3.amazonaws.com/styles/news7_inner/concept_car_2020-wide.jpg?itok=HVf_codM and the url returns a xml from amazons3

I checked it with disabling the cname first and then uploading the file and then tried to access the node
the image is not returned and after enabling the cname, it prepended my bucket name and worked in pristine order...

This is how the older AmazonS3 module worked... I mean bucketname.s3.amazonaws.com/....../.....

**Comment by crystalpaladin** [comment]
I'm kinda confused...
I thought these both are valid bucket urls
http(s)://&lt;bucket&gt;.s3.amazonaws.com/
http(s)://s3.amazonaws.com/&lt;bucket&gt;/

Or did amazon AWS changed their api?

**Comment by deviantintegral** [comment]
All of the buckets I was testing with had dots in their names. It turns out the SDK generates the URLs you see if there are no dots, and the URLs I was seeing if their was a dot.

PR in a moment.

**Comment by crystalpaladin** [comment]
oh boyyy. that was a very quick response and a very quick commit. I'll be happy to see this in the next beta release

**Comment by deviantintegral** [comment]
Tests passed, so I merged this in.

**Comment by crystalpaladin** [comment]
The Issue is still on the loose. Is it possible to open the issue again?
Might want to look at the following:

File: StreamWrapperConfiguration.php
Function: fromDrupalVariables()
Code Line no range to refer: 340 - 359
Code under consideration:Line 357

$config->setDomain('s3.amazonaws.com');

Seems if the cname is not set, the code assigns the domain as 's3.amazonaws.com' at line no 357
This might've by-passed the patched code and leaves the situation unchanged

**Comment by crystalpaladin** [comment]
@deviantintegral The previous patch You've applied for the function fromConfig() can be modified and applied for the function fromDrupalVariables().
file: StreamWrapperConfiguration.php

code (from line 355 to 365):

``` php
else {
    // If the bucket does not contain dots, the S3 SDK generates URLs that
    // use the bucket name in the host.
    if (strpos($config->getBucket(), '.') === FALSE) {
        $config->setDomain($config->getBucket() . '.' . 's3.amazonaws.com');
    }
    else {
        $config->setDomain('s3.amazonaws.com');
    }
}
```

I've included this piece of code in the module and it works fine...
Please include it after optimizing it in the next beta release...

**Comment by deviantintegral** [comment]
Good catch. I really should have pulled that code into a method so I couldn't miss it.

I've got myself set up with a bucket with no dot, and will have a PR in a moment that looks to solve this issue for me.

**Comment by crystalpaladin** [comment]
Cool...
I'll check for some more scenarios just in case and report them as early as possible...
1) Setting up CName
2) Integrating CDN
3) Removing the styles folder in drupal setup for images uploaded before amazon setup and check whether it generates images for the same in s3

Is there any other way to migrate existing files to amazons3 or any shortcuts, pointers you know of?

and, by the way... You guys're good peeps and doing a nice work...

**Comment by crystalpaladin** [comment]
Works nice with CName and CDN setup

**Comment by deviantintegral** [comment]
Thanks for following up @crystalpaladin !
